In [3]:
import math
from pathlib import Path

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
dataset_path = Path("../dataset")
accounts_path = dataset_path / "HI-Small_accounts.csv"
sample_transactions_path = dataset_path / "transactions_test_sample.csv"
all_transactions_path = dataset_path / "HI-Small_Trans.csv"
print(f"{accounts_path=}")
print(f"{sample_transactions_path=}")
print(f"{all_transactions_path=}")

accounts_path=PosixPath('../dataset/HI-Small_accounts.csv')
sample_transactions_path=PosixPath('../dataset/transactions_test_sample.csv')
all_transactions_path=PosixPath('../dataset/HI-Small_Trans.csv')

In [18]:
sample_transactions = pd.read_csv(sample_transactions_path, header=None)
all_transactions = pd.read_csv(all_transactions_path)
accounts = pd.read_csv(accounts_path)

In [19]:
sample_transactions.head(20)

,0,1,2,3,4,5,6,7,8,9,10
0,2022/09/01 00:06,21174,800737690,12,80011F990,2848.96,Euro,2848.96,Euro,ACH,1
1,2022/09/01 04:33,21174,800737690,20,80020C5B0,8630.40,Euro,8630.40,Euro,ACH,1
2,2022/09/01 09:14,21174,800737690,20,80006A5E0,35642.49,Yuan,35642.49,Yuan,ACH,1
3,2022/09/01 09:56,21174,800737690,220,8007A5B70,5738987.96,US Dollar,5738987.96,US Dollar,ACH,1
4,2022/09/01 11:28,21174,800737690,1244,80093C0D0,7254.53,US Dollar,7254.53,US Dollar,ACH,1
5,2022/09/01 13:13,21174,800737690,513,80078E200,6990.87,US Dollar,6990.87,US Dollar,ACH,1
6,2022/09/01 14:11,21174,800737690,20,80066B990,12536.92,Euro,12536.92,Euro,ACH,1
7,2022/09/02 15:40,21174,800737690,410,8002CC310,3511.82,Euro,3511.82,Euro,ACH,1
8,2022/09/02 21:23,21174,800737690,1292,8004030A0,16135.09,US Dollar,16135.09,US Dollar,ACH,1
9,2022/09/02 23:10,21174,800737690,1601,800578800,12183.28,US Dollar,12183.28,US Dollar,ACH,1
10,2022/09/03 09:29,21174,800737690,1,800AAF0B0,15197.45,US Dollar,15197.45,US Dollar,ACH,1
11,2022/09/03 14:22,21174,800737690,1420,8006FB970,4717.76,US Dollar,4717.76,US Dollar,ACH,1
12,2022/09/04 07:35,21174,800737690,10,800449990,19332.59,US Dollar,19332.59,US Dollar,ACH,1
13,2022/09/04 09:10,21174,800737690,11852,800AEBA90,300.93,Euro,300.93,Euro,ACH,1
14,2022/09/04 12:03,21174,800737690,10,800692550,2724.99,US Dollar,2724.99,US Dollar,ACH,1
15,2022/09/04 15:48,21174,800737690,11056,8007486D0,15224.53,Euro,15224.53,Euro,ACH,1

In [20]:
all_transactions.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='str')

In [43]:
df1 = sample_transactions[[1, 2]].drop_duplicates()
df2 = sample_transactions[[3, 4]].set_axis([1, 2], axis=1).drop_duplicates()
sample_accounts= pd.concat([df1, df2], ignore_index=True).drop_duplicates()
sample_accounts = sample_accounts.set_axis(["Bank ID", "Account Number"], axis=1)
sample_accounts.head(20)

    Bank ID Account Number
0     21174      800737690
1        12      80011F990
2        20      80020C5B0
3        20      80006A5E0
4       220      8007A5B70
5      1244      80093C0D0
6       513      80078E200
7        20      80066B990
8       410      8002CC310
9      1292      8004030A0
10     1601      800578800
11        1      800AAF0B0
12     1420      8006FB970
13       10      800449990
14    11852      800AEBA90
15       10      800692550
16    11056      8007486D0

In [45]:
sample_accounts = accounts.merge(sample_accounts, on=["Bank ID", "Account Number"], how="inner")
sample_accounts.head(20)

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,China Bank #6,20,80020C5B0,800912E30,Sole Proprietorship #22187
1,Germany Bank #214,11056,8007486D0,8008D3CD0,Sole Proprietorship #5797
2,National Bank of Laramie,10,800692550,800E8B090,Sole Proprietorship #982
3,Netherlands Bank #4,11852,800AEBA90,8006D9F10,Sole Proprietorship #21628
4,Bank of Arkadelphia,1244,80093C0D0,800B07FB0,Corporation #3438
5,National Bank of New Orleans,513,80078E200,800C91940,Partnership #1318
6,National Bank of the East,12,80011F990,800621E60,Corporation #20103
7,National Bank of Pittsburgh,220,8007A5B70,800EAAFE0,Sole Proprietorship #17263
8,Savings Bank of Seattle,1292,8004030A0,80008D3C0,Partnership #538
9,Arbor Savings Bank,1,800AAF0B0,800A88540,Sole Proprietorship #14551
10,Germany Bank #126,410,8002CC310,800636C60,Corporation #20201
11,National Bank of Laramie,10,800449990,80004B6A0,Sole Proprietorship #555
12,Acme Cooperative Bank,1601,800578800,8000C3DE0,Sole Proprietorship #792
13,Golden Bancorp,1420,8006FB970,800FBCC20,Partnership #1223
14,China Bank #6,20,80006A5E0,80099E290,Corporation #21780
15,China Bank #6,20,80066B990,8006053B0,Partnership #24807

In [46]:
sample_accounts.to_csv("../dataset/accounts_test_sample.csv", index=False)

In [49]:
all_transactions.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='str')