In [1]:
import pandas as pd

In [ ]:
# transactions = pd.DataFrame(columns=['Timestamp', 'From Bank', 'From Account', 'To Bank', 'To Account',
#        'Amount Received', 'Receiving Currency', 'Amount Paid',
#        'Payment Currency', 'Payment Format', 'Is Laundering', 'Group ID', 'method'])
# transactions.head()

Empty DataFrame
Columns: [Timestamp, From Bank, From Account, To Bank, To Account, Amount Received, Receiving Currency, Amount Paid, Payment Currency, Payment Format, Is Laundering]
Index: []

# Sample Data
BEGIN LAUNDERING ATTEMPT - GATHER-SCATTER:  Max 10-degree Fan-In  
2022/09/03 05:28,003123,8028AC420,0139342,80EB1E930,1082.12,Swiss Franc,1082.12,Swiss Franc,ACH,1  
2022/09/04 06:05,0214050,805E56740,0139342,80EB1E930,10457.51,Swiss Franc,10457.51,Swiss Franc,ACH,1  
2022/09/04 10:41,022164,8066D7B00,0139342,80EB1E930,5928.97,Swiss Franc,5928.97,Swiss Franc,ACH,1  
2022/09/04 11:30,00220,8002B5EE0,0139342,80EB1E930,18102.93,Swiss Franc,18102.93,Swiss Franc,ACH,1  
2022/09/05 01:28,008805,806689160,0139342,80EB1E930,13631.38,Swiss Franc,13631.38,Swiss Franc,ACH,1  
2022/09/05 11:54,026463,80ED75AC0,0139342,80EB1E930,14619.24,Swiss Franc,14619.24,Swiss Franc,ACH,1  
2022/09/06 07:36,002991,8057BA770,0139342,80EB1E930,743.91,Swiss Franc,743.91,Swiss Franc,ACH,1  
2022/09/06 12:47,014099,80B828DE0,0139342,80EB1E930,10209.43,Swiss Franc,10209.43,Swiss Franc,ACH,1  
2022/09/06 17:24,0021615,80AA05290,0139342,80EB1E930,13837.79,Swiss Franc,13837.79,Swiss Franc,ACH,1  
2022/09/06 21:55,009,806FA9C10,0139342,80EB1E930,7645.05,Swiss Franc,7645.05,Swiss Franc,ACH,1  
2022/09/06 04:09,0139342,80EB1E930,021258,80DA5FC60,1274.98,US Dollar,1274.98,US Dollar,ACH,1  
2022/09/06 04:50,0139342,80EB1E930,003420,80CA4D110,5568.82,US Dollar,5568.82,US Dollar,ACH,1  
2022/09/06 06:15,0139342,80EB1E930,021258,802455070,15290.92,US Dollar,15290.92,US Dollar,ACH,1  
2022/09/06 14:09,0139342,80EB1E930,011,80B503710,1854.59,Euro,1854.59,Euro,ACH,1  
2022/09/08 11:19,0139342,80EB1E930,0010656,8045A70E0,1535493.32,Yen,1535493.32,Yen,ACH,1  
2022/09/08 14:11,0139342,80EB1E930,013264,808E06810,17625.65,US Dollar,17625.65,US Dollar,ACH,1  
2022/09/09 05:18,0139342,80EB1E930,0224555,8110882E0,14635.16,Euro,14635.16,Euro,ACH,1  
2022/09/09 06:01,0139342,80EB1E930,01547,800360060,6398.44,Euro,6398.44,Euro,ACH,1  
2022/09/09 16:51,0139342,80EB1E930,013083,80B91CD20,15757.84,Euro,15757.84,Euro,ACH,1  
2022/09/09 17:03,0139342,80EB1E930,0117299,811C16680,19845.21,US Dollar,19845.21,US Dollar,ACH,1  
2022/09/10 02:09,0139342,80EB1E930,0122332,808C1A610,7433.54,UK Pound,7433.54,UK Pound,ACH,1  
END LAUNDERING ATTEMPT - GATHER-SCATTER  

BEGIN LAUNDERING ATTEMPT - FAN-OUT:  Max 11-degree Fan-Out  
2022/09/03 05:59,011107,80338EC60,013083,802E55FD0,3486.32,Euro,3486.32,Euro,ACH,1  
2022/09/03 07:25,011107,80338EC60,0110,80CFCDFB0,56662.08,Brazil Real,56662.08,Brazil Real,ACH,1  
2022/09/03 10:50,011107,80338EC60,0215064,806FF9890,12200.85,US Dollar,12200.85,US Dollar,ACH,1  
2022/09/03 11:15,011107,80338EC60,0229558,80B7E2CD0,2893.51,US Dollar,2893.51,US Dollar,ACH,1  
2022/09/03 16:19,011107,80338EC60,0030380,80B826C80,15562.35,Yuan,15562.35,Yuan,ACH,1  
2022/09/04 10:34,011107,80338EC60,0137218,80DDAB2B0,7295.42,Swiss Franc,7295.42,Swiss Franc,ACH,1  
2022/09/04 12:49,011107,80338EC60,0240229,80F1AF2E0,11742.49,Swiss Franc,11742.49,Swiss Franc,ACH,1  
2022/09/04 13:56,011107,80338EC60,0112497,804BAFE40,505234.55,Rupee,505234.55,Rupee,ACH,1  
2022/09/04 16:39,011107,80338EC60,0232583,80D3AF4B0,7624.56,US Dollar,7624.56,US Dollar,ACH,1  
2022/09/05 02:23,011107,80338EC60,0017120,8064C6BE0,343988.90,Ruble,343988.90,Ruble,ACH,1  
2022/09/07 05:06,011107,80338EC60,0232154,80D0E9FB0,12858.54,Euro,12858.54,Euro,ACH,1  
END LAUNDERING ATTEMPT - FAN-OUT

In [9]:
group_id = 0
data = []
group_rows = []
with open("../dataset/HI-Small_Patterns.txt", "r") as f:
    row = []
    for line in f:
        if line == "\n":
            continue

        if line.startswith("BEGIN"):
            group_id += 1
            continue

        if line.startswith("END"):
            method = line.split(" - ")[1]
            for r in group_rows:
                r.append(group_id)
                r.append(method.strip())
            data.extend(group_rows)
            group_rows = []
            continue

        row = line.split(',')
        group_rows.append(row)

        
df = pd.DataFrame(data, columns=['Timestamp', 'From Bank', 'From Account', 'To Bank', 'To Account',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering', 'Group ID', 'method'])
df.head()

,Timestamp,From Bank,From Account,To Bank,To Account,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,Group ID,method
0,2022/09/01 00:06,021174,800737690,012,80011F990,2848.96,Euro,2848.96,Euro,ACH,1\n,1,FAN-OUT
1,2022/09/01 04:33,021174,800737690,020,80020C5B0,8630.40,Euro,8630.40,Euro,ACH,1\n,1,FAN-OUT
2,2022/09/01 09:14,021174,800737690,020,80006A5E0,35642.49,Yuan,35642.49,Yuan,ACH,1\n,1,FAN-OUT
3,2022/09/01 09:56,021174,800737690,00220,8007A5B70,5738987.96,US Dollar,5738987.96,US Dollar,ACH,1\n,1,FAN-OUT
4,2022/09/01 11:28,021174,800737690,001244,80093C0D0,7254.53,US Dollar,7254.53,US Dollar,ACH,1\n,1,FAN-OUT

In [10]:
df.shape

(3209, 13)

In [15]:
df[['Group ID']].value_counts().quantile(0.90)

np.float64(22.0)

In [14]:
df[['Group ID']].value_counts().describe()

count    370.000000
mean       8.672973
std        7.656485
min        1.000000
25%        2.000000
50%        6.500000
75%       13.000000
max       32.000000
Name: count, dtype: float64